import { t } from "./locales/strings";

export const tasks = [
  {
    id: 1,
    title: t("task_1_title"),
    description: t("task_1_desc"),
    goal: 1000,
    rewardPC: 1000,
    type: "clicks",
  },
  {
    id: 2,
    title: t("task_2_title"),
    description: t("task_2_desc"),
    goal: 5,
    rewardPC: 5000,
    type: "level",
  },
  {
    id: 3,
    title: t("task_3_title"),
    description: t("task_3_desc"),
    goal: 15000,
    rewardPC: 15000,
    type: "clicks",
  },
  {
    id: 4,
    title: t("task_4_title"),
    description: t("task_4_desc"),
    goal: 5,
    rewardPC: 50000,
    rewardGP: 5,
    type: "upgradeCount",
  },
  {
    id: 5,
    title: t("task_5_title"),
    description: t(""),
    goal: 1,
    rewardPC: 10000,
    rewardGP: 50,
    type: "fingerUpgrade",
  },
  {
    id: 6,
    title: t("task_6_title"),
    description: t("task_6_desc"),
    goal: 3,
    rewardPC: 3000,
    type: "rouletteSpin",
  },
  {
    id: 7,
    title: t("task_7_title"),
    description: t("task_7_desc"),
    goal: 1000000,
    rewardGP: 100,
    type: "clicks",
  },
  {
    id: 8,
    title: t("task_8_title"),
    description: t("task_8_desc"),
    goal: 50000,
    rewardPC: 15000,
    type: "clicks",
  },
  {
    id: 9,
    title: t("task_9_title"),
    description: t("task_9_desc"),
    goal: 10,
    rewardPC: 30000,
    rewardGP: 10,
    type: "level",
  },
  {
    id: 10,
    title: t("task_10_title"),
    description: t("task_10_desc"),
    goal: 20,
    rewardPC: 50000,
    rewardGP: 10,
    type: "level",
  },
  {
    id: 11,
    title: t("task_11_title"),
    description: t("task_11_desc"),
    goal: 250000,
    rewardPC: 50000,
    type: "clicks",
  },
  {
    id: 12,
    title: t("task_12_title"),
    description: t("task_12_desc"),
    goal: 500000,
    rewardPC: 70000,
    type: "clicks",
  },
];
